<?php

namespace ContainerY4isKda;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_6e8Hc8FService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.6e8Hc8F' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.6e8Hc8F'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'Context' => ['privates', '.errored..service_locator.6e8Hc8F.EasyCorp\\Bundle\\EasyAdminBundle\\Context\\AdminContext', NULL, 'Cannot autowire service ".service_locator.6e8Hc8F": it references class "EasyCorp\\Bundle\\EasyAdminBundle\\Context\\AdminContext" but no such service exists.'],
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', false],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'Context' => 'EasyCorp\\Bundle\\EasyAdminBundle\\Context\\AdminContext',
            'doctrine' => '?',
            'em' => '?',
        ]);
    }
}
