<?php

namespace ContainerVZPkLM1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SeslfaWService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.seslfaW' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.seslfaW'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'categorie' => ['privates', 'App\\Repository\\CategorieRepository', 'getCategorieRepositoryService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'reponse' => ['privates', 'App\\Repository\\ReponseRepository', 'getReponseRepositoryService', true],
            'user' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'categorie' => 'App\\Repository\\CategorieRepository',
            'entityManager' => '?',
            'reponse' => 'App\\Repository\\ReponseRepository',
            'user' => 'App\\Repository\\UserRepository',
        ]);
    }
}
