<?php

namespace ContainerVZPkLM1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FL1d4k8Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.FL1d4k8' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.FL1d4k8'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'Context' => ['privates', '.errored..service_locator.FL1d4k8.EasyCorp\\Bundle\\EasyAdminBundle\\Context\\AdminContext', NULL, 'Cannot autowire service ".service_locator.FL1d4k8": it references class "EasyCorp\\Bundle\\EasyAdminBundle\\Context\\AdminContext" but no such service exists.'],
            'mailer' => ['privates', 'mailer.mailer', 'getMailer_MailerService', true],
        ], [
            'Context' => 'EasyCorp\\Bundle\\EasyAdminBundle\\Context\\AdminContext',
            'mailer' => '?',
        ]);
    }
}
